In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage = 100 * A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [23]:
# More broadcasting examples

a = np.array([1,2,3,4])
print(np.shape(a))
print(a + 100)
# As we can see the number 100 has been expanted to a 4 element array like this [100, 100, 100, 100]

(4,)
[101 102 103 104]


In [33]:
# Another example can be add the same number to each column.

b = np.arange(0, 6)
b = b.reshape(2,3)
aux = np.array([100, 200, 300])

answ = b + aux
print(answ)
print("The 100 was added to the first column, the 200 to the second and so on")


[[100 201 302]
 [103 204 305]]
The 100 was added to the first column, the 200 to the second and so on


In [48]:
# The last example will be summing the same row values.
print(b)
aux2 = np.array([[2],
                 [4]])
print(aux2)
print(b + aux2)

[[0 1 2]
 [3 4 5]]
[[2]
 [4]]
[[2 3 4]
 [7 8 9]]
