In [13]:
import numpy as np

# randn(x) generates a random array full of numbers between -1 and 1.
a = np.random.randn(5)
print(a)

[ 0.84910949 -1.98513133  0.36396277 -1.86970598 -0.24366295]


In [16]:
# This is call a rank1 array.
print(a.shape)

(5,)


In [28]:
# This is how to transpose a matrix
a_transpose = a.T
print(a_transpose)

[ 0.84910949 -1.98513133  0.36396277 -1.86970598 -0.24366295]


In [30]:
print(np.dot(a, a.T))
#Because of this is not recomended to work with rank1 arrays.

8.349374285210828


In [35]:
# The best way to avoid the previous example it is using columns vectors like this.

a = np.random.randn(5,1)
print("Raw vector")
print(a)
print("Transpose vector")
print(a.T)

Raw vector
[[ 1.04786557]
 [ 1.49377437]
 [-0.26292699]
 [-0.55592276]
 [-0.37866053]]
Transpose vector
[[ 1.04786557  1.49377437 -0.26292699 -0.55592276 -0.37866053]]


In [36]:
# If we operate the previous vectors we can see now the right operation

print(np.dot(a, a.T))

[[ 1.09802226  1.56527474 -0.27551214 -0.58253233 -0.39678533]
 [ 1.56527474  2.23136187 -0.39275359 -0.83042318 -0.56563339]
 [-0.27551214 -0.39275359  0.0691306   0.1461671   0.09956007]
 [-0.58253233 -0.83042318  0.1461671   0.30905012  0.21050601]
 [-0.39678533 -0.56563339  0.09956007  0.21050601  0.1433838 ]]
